import { session, type Cookie } from 'electron'
import { existsSync, statSync, writeFileSync } from 'node:fs'
import type { YtdlpCookiePlatformId, YtdlpCookiePlatformStatus, YtdlpCookieStatus } from '@koubox/shared'

export const LOGIN_PARTITION = 'persist:koubox-ytdlp-login'

const PLATFORM_RULES: Array<{
  id: YtdlpCookiePlatformId
  label: string
  domains: RegExp
  names: string[]
}> = [
  {
    id: 'youtube',
    label: 'YouTube',
    domains: /(?:^|\.)(youtube\.com|google\.com)$/i,
    names: ['SID', 'HSID', 'SSID', 'APISID', 'SAPISID', '__Secure-1PSID', '__Secure-3PSID', 'LOGIN_INFO']
  },
  {
    id: 'tiktok',
    label: 'TikTok',
    domains: /(?:^|\.)tiktok\.com$/i,
    names: ['sessionid', 'sid_tt', 'sid_guard', 'ttwid']
  },
  {
    id: 'instagram',
    label: 'Instagram',
    domains: /(?:^|\.)instagram\.com$/i,
    names: ['sessionid', 'ds_user_id']
  },
  {
    id: 'facebook',
    label: 'Facebook',
    domains: /(?:^|\.)(facebook\.com|fb\.com)$/i,
    names: ['c_user', 'xs']
  }
]

export function loginSession() {
  return session.fromPartition(LOGIN_PARTITION)
}

export function normalizeProxyRules(proxy: string): string | null {
  const trimmed = proxy.trim()
  if (!trimmed) return null
  return /^https?:\/\//i.test(trimmed) ? trimmed : `http://${trimmed}`
}

export async function applyLoginSessionProxy(proxy: string): Promise<void> {
  const loginSess = loginSession()
  const proxyRules = normalizeProxyRules(proxy)
  if (!proxyRules) {
    await loginSess.setProxy({ mode: 'direct' })
    return
  }
  await loginSess.setProxy({ proxyRules, proxyBypassRules: '<local>' })
}

export async function readLoginCookies(): Promise<Cookie[]> {
  return loginSession().cookies.get({})
}

function cookieDomain(cookie: Cookie): string {
  return (cookie.domain ?? '').replace(/^\./, '').toLowerCase()
}

function platformStatuses(cookies: Cookie[]): YtdlpCookiePlatformStatus[] {
  return PLATFORM_RULES.map((rule) => {
    const matched = cookies.filter((cookie) => {
      if (!cookie.name || !cookie.value) return false
      const domain = cookieDomain(cookie)
      if (!rule.domains.test(domain)) return false
      return rule.names.includes(cookie.name)
    })
    const loggedIn = matched.length > 0
    return {
      id: rule.id,
      label: rule.label,
      loggedIn,
      detail: loggedIn ? `已检测到 ${matched.length} 个登录 cookie` : '未检测到登录 cookie'
    }
  })
}

export function cookiesToNetscape(cookies: Cookie[]): string {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# https://curl.haxx.se/rfc/cookie_spec.html',
    '# This file was generated by Koubox'
  ]
  for (const cookie of cookies) {
    if (!cookie.name || cookie.value === undefined) continue
    const domain = cookie.domain ?? ''
    if (!domain) continue
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const path = cookie.path ?? '/'
    const secure = cookie.secure ? 'TRUE' : 'FALSE'
    const expiry = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0
    lines.push(`${domain}\t${flag}\t${path}\t${secure}\t${expiry}\t${cookie.name}\t${cookie.value}`)
  }
  return `${lines.join('\n')}\n`
}

export async function buildLoginCookieStatus(exportedFile?: string): Promise<YtdlpCookieStatus> {
  const cookies = await readLoginCookies()
  const platforms = platformStatuses(cookies)
  let exported = false
  let exportedAt: string | undefined
  if (exportedFile && existsSync(exportedFile)) {
    exported = true
    exportedAt = statSync(exportedFile).mtime.toISOString()
  }
  return {
    exported,
    exportedAt,
    cookieCount: cookies.length,
    platforms
  }
}

export async function exportLoginCookies(exportedFile: string): Promise<YtdlpCookieStatus> {
  const cookies = await readLoginCookies()
  if (cookies.length === 0) throw new Error('登录窗口中没有任何 cookie。请先打开登录窗口并完成登录。')
  writeFileSync(exportedFile, cookiesToNetscape(cookies), 'utf8')
  return buildLoginCookieStatus(exportedFile)
}
